---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  ports:
    - port: 80
  selector:
    app: app
    version: 2.0.0
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      version: 2.0.0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
        version: 2.0.0  
    spec:
      containers:
      - image: udzhumok/dog-classifier:latest
        name: app
        ports:
        - containerPort: 80
          name: app
