---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  replicas: 2
  selector:
   app: app
   version: v1.0.0
  ports:
    - port: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  selector:
   app: app
   version: v1.0.0
  template:
    spec:
      image: udzhumok/dog-classifier:latest
        ports:
        - containerPort: 8080
